# Generated by Django 4.2.5 on 2023-09-25 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_custom", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscribes",
            options={"verbose_name": "Subscribe", "verbose_name_plural": "Subscribes"},
        ),
    ]
