# Generated by Django 4.2.5 on 2023-09-25 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_custom", "0002_alter_subscribes_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscribes",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="subscribes",
            name="last_name",
        ),
    ]
