# Generated by Django 4.2.5 on 2023-09-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="static/images")),
                ("name", models.CharField(max_length=120)),
                ("priсe", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Accessory",
                "verbose_name_plural": "Accessories",
            },
        ),
        migrations.CreateModel(
            name="Kids",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="static/images")),
                ("name", models.CharField(max_length=120)),
                ("priсe", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Kid",
                "verbose_name_plural": "Kids",
            },
        ),
        migrations.CreateModel(
            name="Mens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="static/images")),
                ("name", models.CharField(max_length=120)),
                ("price", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Men",
                "verbose_name_plural": "Mens",
            },
        ),
        migrations.CreateModel(
            name="Womens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="static/images")),
                ("name", models.CharField(max_length=120)),
                ("priсe", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Women",
                "verbose_name_plural": "Womens",
            },
        ),
    ]
