# Generated by Django 4.2.5 on 2023-09-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessories",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="kids",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="mens",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="womens",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
