# Generated by Django 4.2.5 on 2023-09-25 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_accessories_description_kids_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accessories",
            old_name="priсe",
            new_name="baha",
        ),
        migrations.RenameField(
            model_name="kids",
            old_name="priсe",
            new_name="baha",
        ),
        migrations.RenameField(
            model_name="mens",
            old_name="price",
            new_name="baha",
        ),
        migrations.RenameField(
            model_name="womens",
            old_name="priсe",
            new_name="baha",
        ),
    ]
